Add category service types
openforis/arena-core pull request #15
Opened 2021-03-01 12:25 UTC by sorja

2021-03-02 15:12 UTC, SteRiccio approved these changes

2021-03-03 04:39 UTC, minotogna requested changes

2021-03-03 04:39 UTC, minotogna commented on src/category/importSummary.ts
> +}
add Category prefix

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +}
you don't need this. 
use JobStatus

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +
let's split into 3. CategoryService, CategoryLevelService, CategoryItemService.
so we avoid prefix like level, item to method names.

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +
surveyId is number anywhere used

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +    includeValidation: boolean
call this validate

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +    search: string
draft, validate, limit, offset, search, are all optional

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +  get(options: { validate: boolean; draft: boolean; categoryUuid: string; surveyId: string }): Promise<Category>
draft, validate are optional

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +  getItemsByParentUuid(options: {
this will be just getMany in CategoryItemService

2021-03-03 04:39 UTC, minotogna commented on src/category/service.ts
> +  }): Promise<{ item: CategoryItem; category: Category }>
as we did for other service, do not call methods updateProps, just update and pass the relative Props object

2021-03-03 11:32 UTC, minotogna requested changes

2021-03-03 11:32 UTC, minotogna commented on src/category/categoryItermService.ts
> +    key: string
do we still need key here ?

2021-03-03 11:32 UTC, minotogna commented on src/category/categoryItermService.ts
> +  deleteItem(options: { itemUuid: string; categoryUuid: string; surveyId: number; user: User }): Promise<Category>
call this delete

2021-03-03 11:32 UTC, minotogna commented on src/category/categoryLevelService.ts
> +    key: string
do we still need key here ?

2021-03-03 11:32 UTC, minotogna commented on src/category/index.ts
> +
we need to export the service from index

2021-03-03 11:32 UTC, minotogna commented on src/category/categoryLevelService.ts
> +import { User } from 'src/auth'
call the file levelService

2021-03-03 11:32 UTC, minotogna commented on src/category/categoryItermService.ts
> +import { User } from 'src/auth'
call the file itemService

2021-03-03 11:32 UTC, minotogna commented on src/category/service.ts
> +    key: string
do we still need key here?

2021-03-03 13:05 UTC, SteRiccio approved these changes

2021-03-03 13:33 UTC, minotogna approved these changes

2021-03-03 13:33 UTC, merged