Factory/user
openforis/arena-core pull request #25
Opened 2021-03-09 13:11 UTC by sorja

2021-03-09 13:56 UTC, minotogna commented on src/auth/authGroup.ts
> +export const permissions = {
should these be Enums?

2021-03-10 10:53 UTC, minotogna requested changes

2021-03-10 10:53 UTC, minotogna commented on src/auth/authGroup.ts
> +export const groupNames = {
this is an ENUM. AtuhGroupName

2021-03-10 10:53 UTC, minotogna commented on src/auth/authGroup.ts
>    name: string
this is of type AtuhGroupName

2021-03-10 10:53 UTC, minotogna commented on src/auth/factory.ts
> +  surveys: undefined,
NEVER use undefined as default value

DO NOT ADD undefined or null default values

2021-03-10 10:53 UTC, minotogna commented on src/auth/user.test.ts
> +  expect(user.hasProfilePicture).toBeFalsy()
USE MOCK OBJECTS TO VERIFY VALUES, ALWAYS!

2021-03-10 13:00 UTC, SteRiccio approved these changes

2021-03-10 13:05 UTC, minotogna approved these changes

2021-03-10 13:08 UTC, merged