Factory/category{,Taxonomy, Taxon, VernacularName}
openforis/arena-core pull request #27
Opened 2021-03-09 15:41 UTC by ramirobg94

2021-03-09 15:48 UTC, minotogna commented on src/taxonomy/factory.ts
> +      draft: undefined,
let's not leave undefined here.
when creating objects, they are draft and non published by default

2021-03-09 15:49 UTC, minotogna commented on src/taxonomy/taxon/taxon.test.ts
> +    expect(taxon.props.scientificName).toBe('SCIENTIFICNAME')
why not to use the mock object above instead of hardcoding the expected values ?

2021-03-09 15:50 UTC, minotogna commented on src/taxonomy/taxonomy.test.ts
> +    expect(taxonomy).toHaveProperty('published')
see draft, published comment above

2021-03-10 06:43 UTC, minotogna requested changes

2021-03-10 06:43 UTC, minotogna commented on src/taxonomy/factory.ts
> +      uuid: uuidv4(),
wrap uuid

2021-03-10 06:43 UTC, minotogna commented on src/taxonomy/factory.ts
> +      uuid: uuidv4(),
wrap uuid

2021-03-10 13:20 UTC, sorja approved these changes

2021-03-10 13:36 UTC, minotogna approved these changes

2021-03-10 13:36 UTC, merged