Enhancement / expression function categoryItemProp
openforis/arena-core pull request #52
Opened 2021-03-24 08:30 UTC by SteRiccio

Changes in this pull request:
- added SurveyRefData type to Survey (it is used to store a sort of cache of category and taxon items)
- added categoryItemProp function to record expression evaluator
- function tested with unit tests
- added SurveyBuilder and RecordBuilder in tests to simplify test survey and record creation

2021-03-24 08:57 UTC, minotogna commented on src/survey/survey.ts
> +  indexRefData: SurveyRefData
let's call this just refDdata ?

2021-03-24 09:02 UTC, minotogna requested changes

2021-03-24 09:02 UTC, minotogna commented on src/survey/survey.ts
> +  indexRefData: SurveyRefData
it's optional

2021-03-24 09:02 UTC, minotogna commented on src/survey/factory.ts
> +      },
you don't need this

2021-03-24 09:02 UTC, minotogna commented on src/tests/builder/surveyBuilder/surveyBuilder.ts
> +    })
we need a SurveyRefDataFactory

2021-03-24 09:50 UTC, minotogna commented on src/survey/survey.ts
> +export interface SurveyRefData {
it must be exported from survey/index

2021-03-24 09:55 UTC, SteRiccio commented on src/survey/survey.ts
> +  indexRefData: SurveyRefData
ok

2021-03-24 09:55 UTC, SteRiccio commented on src/survey/factory.ts
> +      },
ok

2021-03-24 09:55 UTC, SteRiccio commented on src/tests/builder/surveyBuilder/surveyBuilder.ts
> +    })
right

2021-03-24 09:55 UTC, SteRiccio commented on src/survey/survey.ts
> +export interface SurveyRefData {
ok

2021-03-24 17:44 UTC, minotogna submitted a review, later dismissed

2021-03-25 08:37 UTC, minotogna approved these changes

2021-03-25 09:29 UTC, minotogna approved these changes

2021-03-25 09:47 UTC, sorja approved these changes

2021-03-25 11:04 UTC, merged