User: password?: string
openforis/arena-core pull request #77
Opened 2021-04-16 10:37 UTC by sorja

## Description
add optional field:
password

2021-04-16 11:42 UTC, SteRiccio submitted a review, later dismissed

2021-04-18 05:57 UTC, minotogna commented on src/auth/user.ts
> +  invitationExpired?: boolean
I think it's better that user has a property invitation. e.g.

```typescript
interface User {
...
invitation?: UserInvitation
} 

interface UserInvitation {
expired: boolean
}
```

2021-04-19 07:11 UTC, SteRiccio approved these changes

2021-04-19 07:37 UTC, minotogna approved these changes

2021-04-19 07:38 UTC, minotogna requested changes

2021-04-19 07:38 UTC, minotogna commented on src/auth/user.ts
> +export interface UserInvitation {
this must be exported from index

2021-04-19 08:00 UTC, minotogna approved these changes

2021-04-19 08:24 UTC, SteRiccio approved these changes

2021-04-19 08:25 UTC, merged