Feature/activity log types
openforis/arena-core pull request #90
Opened 2021-05-07 09:24 UTC by sorja

## Description
Create types/interfaces for ActivityLog
Add test for ActivityLogFactory

Minor: Refactor some imports on entry `index.ts`

## Types of changes

- [ ] Docs change
- [x] Refactoring
- [ ] Dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How has this been tested
Unit tests

#### Do you consider this PR needs further testing?

- [x] No
- [ ] Yes

## Disclaimer

Part of #CU-j76qcq

2021-05-07 09:24 UTC, minotogna commented
Task linked: [CU-j76qcq Survey create](https://app.clickup.com/t/j76qcq)

2021-05-08 21:34 UTC, SteRiccio approved these changes

2021-05-08 21:34 UTC, SteRiccio commented on src/activityLog/factory.ts
> +    const defaultProps = {
it should be defaultParams

2021-05-09 12:40 UTC, minotogna requested changes

2021-05-10 07:18 UTC, sorja commented on src/activityLog/factory.ts
> +export const ActivityLogFactory: Factory<ActivityLog<ActivityLogType, any>, ActivityLogFactoryParams> = {
Let's keep factory (as discussed in daily)

2021-05-10 14:34 UTC, minotogna requested changes

2021-05-10 14:34 UTC, minotogna commented on src/activityLog/activityLog.ts
> +  chainNodeDef = 'chainNodeDef',
please, see in arena

2021-05-10 14:34 UTC, minotogna commented on src/activityLog/factory.ts
> +  system: boolean
system is optional

2021-05-11 21:54 UTC, SteRiccio submitted a review, later dismissed

2021-05-13 07:57 UTC, minotogna requested changes

2021-05-13 07:57 UTC, minotogna commented on src/activityLog/factory.ts
> +  createInstance: (params: ActivityLogFactoryParams): ActivityLog<ActivityLogType, any> => {
you need to find a way to use generics for type and content.

2021-05-13 07:57 UTC, minotogna commented on src/survey/index.ts
> +export { validateNewSurvey } from './surveys/validator'
you need to export the SurveyValidator object. not each single method

2021-05-13 07:57 UTC, minotogna commented on src/survey/service.ts
> +  getManyByName(options: { surveyName: string }): Promise<Array<Survey> | null>
name should be added to getMany method. do not add another method

2021-05-13 07:57 UTC, minotogna commented on src/survey/surveys/index.ts
> +  validateNewSurvey,
create a SurveyValidator object.

2022-03-23 09:33 UTC, closed without merging